### ISSUE TITLE
プロダクトネームいい感じのにする

### ISSUE THREAD

**Issue by 75asa** [yuraki148/newChannelBot#11]
一旦、 new だけじゃないので Slack channel の名前 `channel-watcher` でいく
いいアイディア出たら、コメントしてく @75asa @yuraki148

**Comment by 75asa** [comment]
@yuraki148 いくつか考えてみました、どうでしょ
- channel-event-catcher
- channel-notifyer
- channel-paperboy
- channel-watcher

**Comment by yuraki148** [comment]
@75asa 
すごいなんとなくですが、上記候補の中では
channel-notifyer
が良いなと思いました！

**Comment by 75asa** [comment]
ではそれで！

**Comment by 75asa** [comment]
@yuraki148 リポジトリの名前だけ変えておいて欲しいです〜
終わったらこのイシューはクローズで

**Comment by yuraki148** [comment]
変更したのでクローズします！
