### ISSUE TITLE
cold start 問題を解消

### ISSUE THREAD

**Issue by 75asa** [yuraki148/newChannelBot#6]
ワーミングしたりして、使われてない時間がしばらく続いたあとにイベントが発火した際に同じ内容が Slack に投稿されないようにする

Glitch がワーミングできるかはわからないけど、 Firebase, Heroku, Cloud Run など他のホスティングでは Cron で簡単なリクエストをおくったりしてた

**Comment by yuraki148** [comment]
@75asa 
2点分からないことがある為質問させてください！

①ワーミングとは何でしょうか？（検索しても見つけられなかった為教えていただきたいです）

②Cronについて。これを行うことで定期的にコードを実行してくれるようになり、今回であればGlitchのサーバーを寝かせないことができるという認識であっていますでしょうか？（下記記事を参考にしています）

- https://nju33.com/glitch/%E3%81%A7%E3%81%8D%E3%82%8B%E3%81%A0%E3%81%91%E9%95%B7%E6%99%82%E9%96%93%E5%8B%95%E3%81%8B%E3%81%99

- https://benborgers.com/blog/glitch-cron-job/

**Comment by 75asa** [comment]
@yuraki148 
1): warming, warm up とか呼ばれたりしてます
e.g. [Warming Up a Java Process](https://devcenter.heroku.com/articles/warming-up-a-java-process)

2): そうですね、認識あっています〜 👍🏾

**Comment by yuraki148** [comment]
ありがとうございます！

**Comment by yuraki148** [comment]
対処方法が全く分からず探し続けた結果、下記記事を発見しました。Glitchでは常時サーバーを起動するために外部サービスを使用することは禁止されてしまったようです。（常時起動したい場合は有料版にする必要あり。）
https://botwiki.org/blog/glitch-banning-use-of-pinging-services/

そのためBotをGlitchではなく他のプラットフォームで構築し直す必要がありそうです。

**Comment by yuraki148** [comment]
comment test

**Comment by yuraki148** [comment]
test

**Comment by 75asa** [comment]
> 対処方法が全く分からず探し続けた結果、下記記事を発見しました。Glitchでは常時サーバーを起動するために外部サービスを使用することは禁止されてしまったようです。（常時起動したい場合は有料版にする必要あり。）
> https://botwiki.org/blog/glitch-banning-use-of-pinging-services/
> 
> そのためBotをGlitchではなく他のプラットフォームで構築し直す必要がありそうです。

Cloud Run, Heroku, Firebase Functions, AWS Lambda w/ Serverless Framework, Google App Engine a.k.a. GAE. Azure Functions とかあたりかな？

**Comment by yuraki148** [comment]
Herokuのアドオン「Advanced Scheduler」を使用してコールドスタート問題を解決しようと考えております。
※参考リンク：https://qiita.com/kawadumax/items/616b4652676eb684834e

そしてこのアドオンを追加しようとしたところ下記メッセージが表示され追加できない状況です。
使用しているherokuアカウント：友貴 浦木(yuki.uraki@tam-bourine.co.jp)

> Item could not be created:
> Please verify your account to install this add-on plan (please enter a credit card) For more information, see https://devcenter.heroku.com/categories/billing Verify now at https://heroku.com/verify

クレジットカード情報を登録してくれとのことですが、この場合個人カードの登録でしょうか？それとも別途管理部への申請手続きなど必要でしょうか？

ご確認お願いいたします。

**Comment by 75asa** [comment]
個人カード可能なので先ずはそちらで進めてください〜

**Comment by yuraki148** [comment]
承知いたしました！

Advanced Schedulerの設定が完了し、30分事にアプリを起動する様に設定したためコールドスタート問題は解決できたと思います！
